Find unit by ID
hitmeister/api-sdk-php pull request #81
Opened 2020-04-10 23:13 UTC by DominicWatts

Find unit by ID function

https://github.com/hitmeister/api-sdk-php/issues/79

2020-04-29 10:57 UTC, johnholiver commented on src/Namespaces/UnitsNamespace.php
> +	public function find($idOffer = null, $embedded = null, $limit = 30, $offset = 0)
```suggestion
	public function findByIdOrder($idOffer = null, $embedded = null, $limit = 30, $offset = 0)
```

2020-04-29 10:58 UTC, johnholiver commented on tests/Namespaces/UnitsNamespaceTest.php
> +    public function testFind()
```suggestion
    public function testFindByIdOffer()
```

2020-04-29 10:59 UTC, johnholiver commented on tests/Namespaces/UnitsNamespaceTest.php
> +		$result = $namespace->find('136', ['item']);
```suggestion
		$result = $namespace->findByIdOffer('136', ['item']);
```

2020-04-29 11:06 UTC, johnholiver requested changes
Hello Dominic, thanks for submitting a PR.

In order for me to approve, I need to make sure that the changes follow a certain standard.
I've requested in this review for a refactor over the name of the method, from `find()` to `findByIdOrder`, making it more descriptive. Additionally, I've suggested removing the default null value for `$idOffer` as a complement to the specificity of the change above.

Finally, it could be understood that you wanted to make a generic find, for situations where no parameter is passed. But in that case, I'd recommend having yet another method without the filters ($idItem, $idOffer, or $ean) in the method signature.

2020-04-29 19:31 UTC, DominicWatts commented
Updated to findByIdOffer

2020-05-04 07:29 UTC, johnholiver approved these changes

2020-05-15 07:16 UTC, DominicWatts commented
Not sure if you are expecting me to do anything else

2020-06-30 14:48 UTC, merged

2020-06-30 14:49 UTC, NastiaNovik commented
@DominicWatts  thank you for your contribution and sorry for the delay.